## Basic Configuration

baseurl = "https://collinschaafsma.com"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Collin Schaafsma"
title = "Collin Schaafsma"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Collin Schaafsma"
intro = ""
description = "As a software engineer and business owner, I have been fortunate to work on many amazing projects with inspiring people, from early-stage startups to Fortune 500 companies and everything in between. I have owned a successful software development consultancy and even a custom bicycle frame company. I consider myself a proud generalist and a lifelong learner. I love building things and serving my teams!"
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "I build software, products, teams, and businesses."
keywords = "leadership,engineering,software engineering,builder,collin,schaafsma"

## Social Accounts
[params.social]
github = "collinschaafsma"
instagram = "backforty.life"
linkedin = "collinschaafsma"
email = "schaafsma@gmail.com"

## Extras
[params.extra]
copyright = "© 2021. Collin Schaafsma. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = false

## Main Menu
[menu]
    [[menu.main]]
        name = "blog"
        weight = 100
        url = "/blog/"
    [[menu.main]]
        name = "about"
        weight = 200
        url = "/about/"
